# Generated by Django 3.1.7 on 2021-03-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlist",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="productlist",
            name="price_id",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="productlist",
            name="product_recurring",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
