# Generated by Django 3.1.7 on 2021-03-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20210305_0737"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productlist",
            old_name="product_recurring",
            new_name="price_recurring",
        ),
    ]
