# Generated by Django 3.1.7 on 2021-03-05 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0003_auto_20210305_0742"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200, unique=True)),
                ("address", models.CharField(max_length=500)),
                ("phone", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
