# Generated by Django 3.1.7 on 2021-03-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_customerlist_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerlist",
            name="customer_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
