# Generated by Django 3.1.7 on 2021-03-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_auto_20210305_0954"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerlist",
            name="name",
        ),
    ]
