# Generated by Django 3.1.7 on 2021-03-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_remove_customerlist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerlist",
            name="phone",
            field=models.IntegerField(max_length=12),
        ),
    ]
