# Generated by Django 3.1.7 on 2021-03-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_productlist_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionlist",
            name="customer",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="subscriptionlist",
            name="price",
            field=models.IntegerField(),
        ),
    ]
