# Generated by Django 3.1.7 on 2021-03-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_auto_20210308_0938"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionlist",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="subscriptionlist",
            name="price_id",
        ),
        migrations.AddField(
            model_name="subscriptionlist",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="payments.customerlist",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionlist",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="payments.productlist",
            ),
        ),
    ]
