# Generated by Django 3.1.7 on 2021-03-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_auto_20210308_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerlist",
            name="token_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
